In [2]:
a = 10
b = 20
c = a*b
print(c)

200


In [3]:
from keyword import kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [4]:
help('keywords')



Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [ ]:
# identifier
# keywords
# operators
    # 1.Arithmatic: +, -, *, /, **, //, %
    # 2.Relational: ==, !=, <, >, >=, <=
    # 3.Assignment: =, +=, -=, *=,.....
    # 4.Logical: and, or, not
    # 5.Membership: in, not in
    # 6.Bitwise: &, |, ^, ~, <<, >>
    # 7.identity: is, is not
# datatypes
    #numeric: int, float, complex(iota=j)
    #sequences: 
        #str: immutable collection of character '', "", ''' '''
        #[] list: mutable and unstructured collection of heterogenous elements
        #() tuple: immutable and unstructured collection of heterogenous elements
    #mapping:
        #{} dictionary: mutable and unstructured collection of key value pairs
    #set:
        #{} set: unordered collection of unique items
    #booleans:
        #bool: true, false
    #empty data:
        #none type: none
# data operations(collections)
    #1.item accessing
    #2.item insertion(indexing, slicing, subcripting)
    #3.item assignment(only with the mutable)
    #4.item deletion
# datatype Built-in func
    #str: upper, lower, find, split, strip, join, format, count
    #list: append, sort, count, copy, insert, remove, index, pop
    #tuple: count, index
    #dict: keys,values, update, get, pop
    #set: add, difference, union, pop, remove

In [17]:
a = 34
b = 34.5
c = 34 + 5j
d = 'hello'
e = [3,4,5]
f = (3,4,5)
g = {3: [4,5]}
h = {3,4,5}

In [24]:
g

{3: [4, 5]}

In [25]:
g['a'] = 44
g

{3: [4, 5], 'a': 44}

In [26]:
list(g.keys())[0]

3

In [27]:
g.get('z','oh no')


'oh no'

In [28]:
g.get('z',)   ##none

In [42]:
d.upper()

'HELLO'

In [23]:
'-'.join('wars')
'#'.join('hi this is ml learning'.split())
'hi this is ml learning'.replace(' ', '#')
d.count('l')

2

In [15]:
## string formatting
x=10
y=20
# z = 'the no is 20 to 30'

# (format specifier)----depricated
z = 'the no is %d to %d'%(x,y)

# using format function
z = 'the no is {} to {}'
z = z.format(x,y)

z = 'the no is {} to {}'.format(x,y)

z1 = 'the no is {0} to {1} but this is {0}'
z1 = z1.format(x,y)

# using f-string
f'anything'
zf = f'the no is {x} to {y} but this is{x}'
zf


'the no is 10 to 20 but this is10'

In [19]:
e.append(2)
e

[3, 4, 5, 45, 2]

In [20]:
e.sort()
e

[2, 3, 4, 5, 45]

In [21]:
e.sort(reverse=True)
e

[45, 5, 4, 3, 2]

In [22]:
e1 = ['hi', 'awesome', 'good', 'how']
e1.sort(key=len, reverse=True)
e1

['awesome', 'good', 'how', 'hi']

In [29]:
e3 = e
e3

[45, 5, 4, 3, 2]

In [30]:
e3.append(60)
e3

[45, 5, 4, 3, 2, 60]

In [31]:
e

[45, 5, 4, 3, 2, 60]

In [33]:
e4 = e.copy()
e4.append(8)
e4

[45, 5, 4, 3, 2, 60, 8]

In [ ]:
# deep copy vs shallow copy

In [1]:
s='468hi3.4'
a=[4,6,8,'hi',3.4]
b=(4,6,8,'hi',3.4)
c={4:6, 8:['hi',3.4]}
d={4,6,8,'hi',3.4}

In [3]:
type(s), type(a), type(b), type(c), type(d)

(str, list, tuple, dict, set)

In [4]:
len(s), len(a), len(b), len(c), len(d)

(8, 5, 5, 2, 5)

In [6]:
s += 'k'
s

'468hi3.4kk'

In [7]:
s[3:]

'hi3.4kk'

In [9]:
s = s[:3] + 'nancy' + s[3:]
s

'468nancynancyhi3.4kk'

In [10]:
a

[4, 6, 8, 'hi', 3.4]

In [12]:
a += ['bye']
a

[4, 6, 8, 'hi', 3.4, 'bye']

In [13]:
a = a[:2] = [39] + a[2:]
a

[39, 8, 'hi', 3.4, 'bye', 'hi', 3.4, 'bye']

In [14]:
b

(4, 6, 8, 'hi', 3.4)

In [17]:
b += ('bye',)
b

(4, 6, 8, 'hi', 3.4, 'bye')

In [18]:
(*b,*b)

(4, 6, 8, 'hi', 3.4, 'bye', 4, 6, 8, 'hi', 3.4, 'bye')

In [19]:
(*a,*b)

(39, 8, 'hi', 3.4, 'bye', 'hi', 3.4, 'bye', 4, 6, 8, 'hi', 3.4, 'bye')

In [20]:
(*a,*b,*s)

(39,
 8,
 'hi',
 3.4,
 'bye',
 'hi',
 3.4,
 'bye',
 4,
 6,
 8,
 'hi',
 3.4,
 'bye',
 '4',
 '6',
 '8',
 'n',
 'a',
 'n',
 'c',
 'y',
 'n',
 'a',
 'n',
 'c',
 'y',
 'h',
 'i',
 '3',
 '.',
 '4',
 'k',
 'k')

In [21]:
c[99] = [86,'elvalue']
c

{4: 6, 8: ['hi', 3.4], 99: [86, 'elvalue']}

In [22]:
c2 = {'a':45,'b':35}
print(c)
print(c2)

{4: 6, 8: ['hi', 3.4], 99: [86, 'elvalue']}
{'a': 45, 'b': 35}


In [23]:
{**c,**c2}

{4: 6, 8: ['hi', 3.4], 99: [86, 'elvalue'], 'a': 45, 'b': 35}

In [ ]:
# (*args, **kwargs)

In [ ]:
# strings and list are concatenate bye + sign
# but dict and set are not

In [24]:
s

'468nancynancyhi3.4kk'

In [33]:
# item assignment
# s[0] = 'A' # not applicable
# a[0] = 'A' # done
# b[0] = 'A' # not possible
# c[4]= 66   # done

# item deletion
# del s[0]     # not possible
# del a[0]     # done
# del b[0]     # not possible
# del c[4]     # done




In [34]:
m = None

In [35]:
True

True

In [36]:
bool('False')

True

In [39]:
print(bool(' '),
bool([]),
bool({}),
bool(()),
bool(-1),
bool(45),
bool([()]),)

True False False False True True True


In [28]:
s = 'A sample python statement'
s

'A sample python statement'

In [29]:
#slicing s[start : stop(not included) : stepsize]
##### s[0 : end : +1]
##### s[end : 0 : -ve]
s[2:8:1]

'sample'

In [30]:
s[:8]

'A sample'

In [31]:
s[8:]

' python statement'

In [33]:
s[-9:]

'statement'

In [9]:
s[-11:-17:-1]

'nohtyp'

In [11]:
s[-1:-10:-1]


'tnemetats'

In [13]:
s[:-10:-1]


'tnemetats'

In [9]:
s = 'A sample python statement'
s

'A sample python statement'

In [10]:
s[::-1]

'tnemetats nohtyp elpmas A'

In [11]:
s[-1:-26:-1]

'tnemetats nohtyp elpmas A'

In [13]:
p = [45,[[[[['1','01'],9],34]]]]

In [17]:
p[-1][0][0][0]

[['1', '01'], 9]

In [18]:
d1 = [{'a':34},66,{'66':[{'00':[98,'hi']},'awesome',{'m':'n'}]}]

In [27]:

d1[-1]

{'66': [{'00': [98, 'hi']}, 'awesome', {'m': 'n'}]}

In [ ]:
# Conditional statement
#     1.if-elif-else
# looping
#     1.while-else
#     2.for-else
#     3.continue/break
# error handling


In [1]:
a = [4,'hi','nice',34]
b = []
for i in range(len(a)):
    b.append(a[i]*2)
b    

[8, 'hihi', 'nicenice', 68]

In [2]:
a * 2

[4, 'hi', 'nice', 34, 4, 'hi', 'nice', 34]

In [4]:
# Comprension
# For-Loop statement which are of one liner

# list comprension
#   [output for loop] - map
#   [output for loop if-condition] - Filter 
# dictionary
#   {key_op:value_op for loop}
# set
#   (output for loop)
# generator
#   (output for loop)



b = [val*2 for val in a]
b

[8, 'hihi', 'nicenice', 68]

In [6]:
k = [4,7,3,67,34,5,7,35,9,8]
k[0]%2==0

True

In [11]:
p = [val for val in k if not val % 2]
p

[4, 34, 8]

In [10]:
p = [val for val in k if val % 2 and val>10]
p

[67, 35]

In [12]:
p = []
for val in k:
    if val%2 == 0:
        p.append(val // 2)
    else:
        p.append(val * 2)
p            

[2, 14, 6, 134, 17, 10, 14, 70, 18, 4]

In [13]:
# statement1 if-cond else statement 2
p = [val * 2 if val%2 == 1 else val // 2 for val in k] 
p

[2, 14, 6, 134, 17, 10, 14, 70, 18, 4]

In [15]:
p = [val * 2 if val%2==1 else (val//2 if val<20 else val) for val in k ]
p

[2, 14, 6, 134, 34, 10, 14, 70, 18, 4]

In [16]:
k

[4, 7, 3, 67, 34, 5, 7, 35, 9, 8]

In [ ]:
{val:val**2 for val in k if val % 2 ==4}

In [17]:
# user define function

def function_name():
    print('abc')

In [19]:
function_name()

abc


In [20]:
a=10
while a>5:
    pass

KeyboardInterrupt: 

In [21]:
def one(val1,val2):
    return val1 * val2

In [22]:
one(4,5)

20

In [23]:
x = one(4,5)

In [24]:
y = function_name()

abc


In [25]:
print(x,y)

20 None


In [27]:
def two(val1,val2):
    return (val1 * val2) + val1

In [29]:
two(val2=10 , val1=20)

220

In [30]:
two(12,13)

168

In [33]:
two(12,val2=10)

132

In [34]:
def two(val1=10,val2=20):
    print('abcdd')
    return (val1 * val2) + val1

In [40]:
two(val2=10,val1=20)

220

In [45]:
def abc(x=10,*v,**u):
    return [i*x for i in v], u

In [46]:
abc(2,3,5)

([6, 10], {})

In [47]:
abc(3,6,8, somedata = [3,4,5,6])

([18, 24], {'somedata': [3, 4, 5, 6]})

In [ ]:
# Python function can Be 
# 1. Assignment as a Value
# 2. Taken as input argument in another function
# 3. Define inside another function
# 4. Return a function as output from another function

In [1]:
def abc():
    print('hi')

In [2]:
abc()

hi


In [3]:
k=abc

In [4]:
abc

<function __main__.abc()>

In [5]:
k

<function __main__.abc()>

In [6]:
k()

hi


In [7]:
def xyz(f):
    f()

In [8]:
xyz(f=abc)

hi


In [12]:
def pqr():
    def qrp():
        print('hello')
    qrp()
pqr()    

hello


In [9]:
def pqr():
    def qrp():
        print('hello')
    return qrp    

In [10]:
x = pqr()
x

<function __main__.pqr.<locals>.qrp()>

In [11]:
x()

hello


In [ ]:
# Annonymous function - Lambda Expressions
# Lambda inp_args : output (returned)

# its aways one liner
# always return
# input argument can be multiple, optional, keyword, named except
# output can be simple/conditional/compressional

In [13]:
def doubler(x):
    return x*2

m = doubler(34)
print(m)

68


In [14]:
doubler_L = lambda x : x*2
doubler_L

<function __main__.<lambda>(x)>

In [15]:
doubler_L(34)

68

In [16]:
oddeve = lambda x : 'Odd' if x%2 else 'even'
oddeve(45)

'Odd'

In [17]:
k = lambda : print('hi')
k1=k()


hi


In [18]:
m= k()
print(m)

hi
None


In [ ]:
# scope of variables
# -global
# -local
# -nonlocal

In [19]:
x = 10
def abc():
    print(x)

In [20]:
x=10
def abc():
    x=30

print(x)
abc()
print(x)    

10
10


In [21]:
x=10
def abc():
    global x
    x=30

print(x)
abc()
print(x)    

10
30


In [23]:
x=10
def abc():
    #global x
    x=30
    y=15
    def xyz():
        y=20
        print('from xyz', x)
    xyz() 
    print(y)   

print(x)
abc()
print(x)   

10
from xyz 30
15
10


In [24]:
x=10
def abc():
    #global x
    x=30
    y=15
    def xyz():
        nonlocal y
        y=20
        print('from xyz', x)
    xyz() 
    print(y)   

print(x)
abc()
print(x)   

10
from xyz 30
20
10


In [ ]:
# !python -m pip install numpy
# !pip install numpy

In [29]:
import numpy

In [30]:
import keyword

In [31]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [33]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [35]:
from keyword import kwlist, iskeyword as isk
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [36]:
import numpy as np

In [39]:
a = np.array([])
a

array([], dtype=float64)

In [40]:
b = np.array([3,4,5,6])
b

array([3, 4, 5, 6])

In [44]:
len(a),len(b)

(0, 4)

In [45]:
a.dtype

dtype('float64')

In [46]:
b.shape

(4,)

In [47]:
b.size

4

In [48]:
a.ndim

1

In [49]:
b.ndim

1

In [51]:
c = np.array([[2,3,4], [5,6,7], [8,9,0]])
c

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [52]:
c.shape

(3, 3)

In [53]:
d = np.array([[[2],[3],[4]], [[5],[6],[7]], [[8],[9],[0]]])
d

array([[[2],
        [3],
        [4]],

       [[5],
        [6],
        [7]],

       [[8],
        [9],
        [0]]])

In [54]:
d.shape

(3, 3, 1)

In [55]:
d = np.array([[[2,20],[3,30],[4,40]],
               [[5,50],[6,60],[7,70]],
               [[8,80],[9,90],[0,10]]])
d

array([[[ 2, 20],
        [ 3, 30],
        [ 4, 40]],

       [[ 5, 50],
        [ 6, 60],
        [ 7, 70]],

       [[ 8, 80],
        [ 9, 90],
        [ 0, 10]]])

In [57]:
c.sum(axis=1)

array([ 9, 18, 17])

In [58]:
c.mean(axis=1)

array([3.        , 6.        , 5.66666667])

In [59]:
c

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [60]:
c[0][1]

3

In [61]:
c[0:2, -1]

array([4, 7])

In [63]:
c[0:2,-1:]

array([[4],
       [7]])