In [2]:
import numpy as np

In [2]:
a = np.array([8,6,5])

In [3]:
a

array([8, 6, 5])

In [5]:
a1 = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
a1

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [6]:
a1.shape

(4, 3)

In [6]:
b = np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
b

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [10]:
b.shape

(3, 3, 2)

In [11]:
a1[1,0]

9

In [12]:
a1[1,0:3:1]

array([9, 3, 5])

In [13]:
a1[1,:]

array([9, 3, 5])

In [17]:
a1[0:4:1,2]

array([ 4,  5, 17,  8])

In [20]:
a1[0:4:1,2].shape

(4,)

In [25]:
a1[0:4:1,2:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [26]:
a1[0:4:1,2:3]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [27]:
a1[0:4:1,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [29]:
b[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [34]:
b[1:3:1,2:3:1]

array([[[  5,  51]],

       [[ 13, 131]]])

In [48]:
b[1:1:1,2:1:1]

array([], shape=(0, 0, 2), dtype=int32)

In [35]:
x = [3,5,9]

In [39]:
a+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [40]:
a1

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [42]:
a1[0,:] = [30,40,50]
a1

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [44]:
a1[:,0] = [1,2,3,4]
a1

array([[ 1, 40, 50],
       [ 2,  3,  5],
       [ 3, 15, 17],
       [ 4, 31,  8]])

In [46]:
a1[:2,1:] = [[202,303],[404,505]]
a1

array([[  1, 202, 303],
       [  2, 404, 505],
       [  3,  15,  17],
       [  4,  31,   8]])

In [13]:
np.append(a1,[[1,1,1]], axis = 0) # zero to add rowwise

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8],
       [ 1,  1,  1]])

In [12]:
np.append(a1,[[1],[1],[1],[1]], axis = 1 )

array([[ 3,  8,  4,  1],
       [ 9,  3,  5,  1],
       [11, 15, 17,  1],
       [19, 31,  8,  1]])

In [8]:
a1

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [52]:
np.delete(a1,1,0)

array([[  1, 202, 303],
       [  3,  15,  17],
       [  4,  31,   8]])

In [55]:
np.delete(a1,0,1)

array([[202, 303],
       [404, 505],
       [ 15,  17],
       [ 31,   8]])

In [56]:
np.delete(a1,3,axis=0)

array([[  1, 202, 303],
       [  2, 404, 505],
       [  3,  15,  17]])

In [57]:
a1.reshape(6,2)

array([[  1, 202],
       [303,   2],
       [404, 505],
       [  3,  15],
       [ 17,   4],
       [ 31,   8]])

In [58]:
a.dtype

dtype('int32')

In [60]:
a1.astype('uint16')

array([[  1, 202, 303],
       [  2, 404, 505],
       [  3,  15,  17],
       [  4,  31,   8]], dtype=uint16)

In [61]:
a1.mean()

124.58333333333333

In [62]:
a1.mean(axis=0)

array([  2.5 , 163.  , 208.25])

In [63]:
a1.std(axis=1)

array([125.52379146, 217.25918981,   6.18241233,  11.8977122 ])

In [64]:
# Nutshell
## We craete arrays
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arrange()
# 5. np.linspace()
# 6. np.random.randint()
# Arrays have some attributes and function

In [14]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [15]:
np.random.randint(1,15,[3,4])

array([[12, 11, 11,  8],
       [10,  9,  3,  3],
       [ 7,  8,  7, 12]])

In [1]:
import numpy as np

In [19]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.random.randint(1,6,1)

array([4])

In [22]:
np.random.randint(1,6,[4,3,2])

array([[[3, 5],
        [3, 4],
        [2, 2]],

       [[4, 2],
        [5, 1],
        [4, 2]],

       [[2, 1],
        [3, 4],
        [1, 3]],

       [[2, 5],
        [1, 5],
        [3, 5]]])

In [23]:
np.random.randint(31,6000,[4,3])

array([[2273,  993, 2976],
       [3034, 5075,  451],
       [2486,   34, 2720],
       [2392, 5412, 5002]])

In [24]:
np.random.randint(31,6000,[4,3])

array([[2186, 3115, 3565],
       [5737, 2209,  427],
       [5118, 1955, 3069],
       [3569, 3629, 2104]])

In [26]:
np.random.seed(10)
np.random.randint(31,6000,[4,3],)

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [27]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [29]:
r = np.loadtxt('somedata.txt',dtype=str)
r

array(['there', 'is', 'some', 'type', 'of', 'data'], dtype='<U5')

In [31]:
r = np.loadtxt('somedata2.txt')
r

array([[45., 34., 56., 67.],
       [35., 78., 76., 45.]])

In [33]:
p = np.random.rand(3,4)
p

array([[0.90864888, 0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632, 0.62628715],
       [0.54758616, 0.819287  , 0.19894754, 0.8568503 ]])

In [35]:
np.savetxt('new.txt',p,delimiter=',')