In [1]:
import numpy as np

In [2]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [3]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#use numpy to generate random num btw 0 and 1
np.random.rand(1)

array([0.14838083])

In [7]:
#use numpy to genrate an array of 25 random numbers sampled from  a standard normal distribution
np.random.randn(25)

array([ 1.30091242, -0.2466168 , -0.89876055,  0.99435005, -0.03249913,
        0.14600507,  2.25708822, -0.51301868, -0.41552303, -0.30649577,
       -0.3571582 , -1.02474825, -0.28460212,  2.02825492,  1.22528263,
       -1.0159791 , -0.98887392,  0.63107578, -1.06248889,  0.92710352,
        0.78734869,  0.02960296, -1.32730741, -1.16669075, -0.95990616])

In [8]:
np.arange(0.01,1.01,0.01).reshape((10,10))

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [9]:
np.arange(0.01,1.01,0.01).reshape((10,10)).sum(axis=0)

array([4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])